name: Publish code
on:
  release:
    types:
    - published

jobs:
  build:
    name: publish
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
    - name: Download
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci.yml
        commit: ${{ github.sha }}
        name: PSModule

    - name: check dir
      shell: pwsh
      run: |
        Get-Item ./*.nupkg | Select-Object -ExpandProperty FullName
