name: Publish code
on:
  release:
    types:
    - published

jobs:
  build:
    name: publish
    runs-on: ubuntu-latest

    steps:
    - name: Download
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci.yml
        commit: ${{ github.sha }}
        name: PSModule
        # path: ${{ github.workspace }}

    - name: check dir
      shell: pwsh
      run: |
        Get-Item ./*.nupkg | Select-Object FullName
        # Get-ChildItem '${{ github.workspace }}' -Recurse -Force
